# Generated by Django 3.2.7 on 2021-09-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_note_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='tag',
            field=models.CharField(max_length=200),
        ),
    ]
