# Generated by Django 3.2.7 on 2021-09-26 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_rename_deleted_notes_deleted_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deleted_Note',
        ),
    ]
