# Generated by Django 3.2.7 on 2021-09-26 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_deleted_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deleted_Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='deleted_note',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.deleted_tag'),
        ),
    ]
